name: digirunner-open-source
services:
  dgr:
    image: tpisoftwareopensource/digirunner-open-source:latest
    ports:
      - "31080:18080"
      - "8080:8080"
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./h2_data:/h2
    command: >
      -Xms1g -Xmx2g
      -DdigiRunner.token.key-store.path=/opt/digirunner/keys
      -Dserver.port=18080
      -Dspring.datasource.url="jdbc:h2:./h2/dgrdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE;Mode=MySQL"
      -Dspring.datasource.username=dba
      -Dspring.datasource.password=1234
      -Dspring.sql.init.mode=never
      org.springframework.boot.loader.launch.PropertiesLauncher
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
